version: '3'

services:
  react_app:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
    container_name: react_app
    volumes:
      - ./volumes/md:/world/postCards/md
      - ./volumes/postFront:/world/public/images/postFront
      - ./volumes/postMark:/world/public/images/postMark