export const ACTION_TYPES = {
  SHIPPING_METHOD: 'SHIPPING_METHOD',
  USE_RAKUTEN_POINT: 'USE_RAKUTEN_POINT',
  USE_COUPON: 'USE_COUPON',
  HANDLE_ERROR_SHOW: 'HANDLE_ERROR_SHOW',
  HANDLE_ERROR_REMOVE: 'HANDLE_ERROR_REMOVE',
}